version: '3.2'
services:
  web1:
    build: .
    container_name: web1
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      GCP_API_KEY: ${GCP_API_KEY}
      MYSQL_HOST: 10.38.58.98
      MYSQL_PORT: 3306
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: orders
    networks:
      server_network:
        ipv4_address: 10.38.58.99
    restart: always
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      server_network:
        ipv4_address: 10.38.58.98
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3396:3306
    environment:
     MYSQL_USER: ${DB_USERNAME}
     MYSQL_PASSWORD: ${DB_PASSWORD}
     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: always
  manager:
    image: mysql:5.7
    working_dir: /app
    volumes:
      - ./start.sh:/app/start.sh:ro
      - ./schema.sql:/app/schema.sql:ro
    entrypoint: /bin/sh
    networks:
      server_network:
        ipv4_address: 10.38.58.110
    environment:
      MYSQL_HOST: 10.38.58.98
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    command: "/app/start.sh"
    restart: "on-failure"
    depends_on:
      - mysql
networks:
  server_network:
    ipam:
      config:
        - subnet: 10.38.58.96/28
